name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            platform: ubuntu-latest
          - target: x86_64-apple-darwin
            platform: macos-latest
          - target: x86_64-pc-windows-gnu
            platform: windows-latest

    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: |
          rustup target add ${{ matrix.target }}

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.target }} --release

      - run: |
          tar caf ./wand-${{ matrix.target }}-${{ inputs.version }}.tar.gz target/${{ matrix.target }}/release/wand 

      - run: |
          ls

      #- uses: actions/upload-artifact@v4
      #  with:
      #    name: wand-${{ matrix.target }}-${{ github.event.release.tag_name }}
      #    path: wand-*
